### ISSUE TITLE
颜色选择器不能打开

### ISSUE THREAD

**Issue by jqueryscript** [fanaiai/xncolorpicker#1]
在某些情况，比如点击页面空白处后再点击颜色选择器后就不能打开。

测试环境：MS Edge和Chrome

**Comment by fanaiai** [comment]
昨天更新没更全，明天更新哦

**Comment by fanaiai** [comment]
> 在某些情况，比如点击页面空白处后再点击颜色选择器后就不能打开。
> 
> 测试环境：MS Edge和Chrome

昨天更新没更全，明天更新哦

**Comment by fanaiai** [comment]
> 在某些情况，比如点击页面空白处后再点击颜色选择器后就不能打开。
> 
> 测试环境：MS Edge和Chrome

已更新
