### ISSUE TITLE
你好, 这个项目是必须基于jquery嘛?

### ISSUE THREAD

**Issue by buuing** [fanaiai/xncolorpicker#3]

**Comment by fanaiai** [comment]
> _No description provided._

目前是基于jquery的，本周内将会更新剔除掉jquery库的版本

**Comment by buuing** [comment]
> 目前是基于jquery的，本周内将会更新剔除掉jquery库的版本

可以的, 给你点赞🤞

**Comment by fanaiai** [comment]
> > 目前是基于jquery的，本周内将会更新剔除掉jquery库的版本
> 
> 可以的, 给你点赞

已更新

**Comment by buuing** [comment]
好的
