### ISSUE TITLE
Get selected color

### ISSUE THREAD

**Issue by softwarea** [fanaiai/xncolorpicker#4]
Hi fanaiai,

thanks for providing such a great looking colorpicker. I really love the design.

I have two questions though:

1. Do you provide an API for reading the currently selected color from a given color picker (assuming that I have many pickers on a page)? I am looking for something like var selColor = $('#myPicker').getColor();
2.  Can I hide the Cancel button, OK button and the color text field? In other words: show predefined colors only.

Best
Ingmar

**Comment by fanaiai** [comment]
> Hi fanaiai,
> 
> thanks for providing such a great looking colorpicker. I really love the design.
> 
> I have two questions though:
> 
> 1. Do you provide an API for reading the currently selected color from a given color picker (assuming that I have many pickers on a page)? I am looking for something like var selColor = $('#myPicker').getColor();
> 2. Can I hide the Cancel button, OK button and the color text field? In other words: show predefined colors only.
> 
> Best
> Ingmar

OK,I will upgrade in 3 days

**Comment by softwarea** [comment]
Oh wonderful. I didn't want to cause you any work though. But I would be very happy. Thank you very much!!

**Comment by fanaiai** [comment]
> Oh wonderful. I didn't want to cause you any work though. But I would be very happy. Thank you very much!!

Hi,Thank you for your issue,I just upgrade the code. If there are any problems please let me know.

There are three new configurations:
hideInputer:true,//hide input field
hideCancelButton:true,//hide Cancel Button
hideConfirmButton:true,//hide Confirm Button


A new function to get current color:
var curcolor=colorpickerins.$$getCurColor()

You can try it like this:

var justpre = new XNColorPicker({
        color: "#008867",
        selector: "#justpre",
        showprecolor: true,//显示预制颜色
        prevcolors: null,//预制颜色，不设置则默认

        historycolornum: 16,//历史条数
        format: 'hsla',//rgba hex hsla,初始颜色类型
        showPalette:false,//显示色盘
        show:false, //初始化显示
        lang:'cn',// cn 、en
        colorTypeOption:'single,linear-gradient,radial-gradient',//

        showhistorycolor: false,//show history colors
        hideInputer:true,//hide input field
        hideCancelButton:true,//hide Cancel Button
        hideConfirmButton:true,//hide Confirm Button
        autoConfirm:true,//If you hide Confirm button,please set autoConfirm to true


        onError: function (e) {

        },
        onCancel:function(color){
            console.log("cancel",color)
        },
        onChange:function(color){
            console.log("change",color)
        },
        onConfirm:function(color){
            console.log("confirm",color)
        }
    })
var justpre=colorpickerins.$$getCurColor()

**Comment by softwarea** [comment]
Hi, wow, that was fast. 

The hideXXX properties work perfectly :)

But I am not sure about the getCurColor() method. It seems like I can only get the color of a color picker which I have stored in a variable. But what if I have multiple color pickers on a page and want to read all their colors? I am looking for someting like this: 

`var $colorpickers = $('.my-color-picker');
$colorpickers.each(function () {
     var color = $(this).getCurColor();
})`

**Comment by fanaiai** [comment]
> Hi, wow, that was fast.
> 
> The hideXXX properties work perfectly :)
> 
> But I am not sure about the getCurColor() method. It seems like I can only get the color of a color picker which I have stored in a variable. But what if I have multiple color pickers on a page and want to read all their colors? I am looking for someting like this:
> 
> `var $colorpickers = $('.my-color-picker'); $colorpickers.each(function () { var color = $(this).getCurColor(); })`

Good idea,update your code,try it like this:
$('.my-color-picker').each(function (i,ele) { var color = ele.colorpicker.$getCurColor(); })

**Comment by softwarea** [comment]
Allrighty. Thank you so much. Works like a charm. So I have everything I need. THX!

Howver, let me suggest something: your picker's design is the nicest I have seen so far! But the API is kind of weird.
Wouldn't you like to improve it a bit? For instance, I would appreciate:

1. Create new  picker: var myPicker = $('#myElement').createColorPicker();
2. Get existing picker: var myPicker = $('#myElement').getColorPicker();
3. In the event handlers, add a reference to the corresponding picker. i.e. onChange: function (this, color)

But again: thx so much!!!

**Comment by fanaiai** [comment]
> Allrighty. Thank you so much. Works like a charm. So I have everything I need. THX!
> 
> Howver, let me suggest something: your picker's design is the nicest I have seen so far! But the API is kind of weird.
> Wouldn't you like to improve it a bit? For instance, I would appreciate:
> 
> 1. Create new  picker: var myPicker = $('#myElement').createColorPicker();
> 2. Get existing picker: var myPicker = $('#myElement').getColorPicker();
> 3. In the event handlers, add a reference to the corresponding picker. i.e. onChange: function (this, color)
> 
> But again: thx so much!!!

Oh,you mean like jQuery plugin , I have removed jQuery from it ,it is actually a native JS plugin,but i will think about it,If I make any improvements , I'll let you know.,Thanks for your suggestions。

**Comment by softwarea** [comment]
Oh, I am sorry. I totally missed that. I saw so many '$'.-signs that I thought all this is jQuery based. So, it's vanilla JS. Totally fine for me. THX again!! Great component.

**Comment by fanaiai** [comment]
> Oh, I am sorry. I totally missed that. I saw so many '$'.-signs that I thought all this is jQuery based. So, it's vanilla JS. Totally fine for me. THX again!! Great component.

Haha,Jquery is too large i dont need so many functions,so i implement some functions and use the same symbol
